### ISSUE TITLE
FTBQBorealis doesn't work with latest FTB Quests version

### ISSUE THREAD

**Issue by Mikaaah** [Hunter19823/FTBQBorealis#1]
Mod refuses to load with latest FTB Quests version, saying it is missing. FTB Quests version : ftb-quests-1605.2.0-build.30-forge
FTBQBorealis Version 1.0.4

[crash-2021-02-24_01.07.17-fml.txt](https://github.com/Hunter19823/FTBQBorealis/files/6032470/crash-2021-02-24_01.07.17-fml.txt)

**Comment by Hunter19823** [comment]
> Mod refuses to load with latest FTB Quests version, saying it is missing. FTB Quests version : ftb-quests-1605.2.0-build.30-forge
> FTBQBorealis Version 1.0.4
> 
> [crash-2021-02-24_01.07.17-fml.txt](https://github.com/Hunter19823/FTBQBorealis/files/6032470/crash-2021-02-24_01.07.17-fml.txt)

This was intentional because the developer of FTB Quests was in the middle of rewriting the mod and therefor was still in beta when I made the latest version.
Now that FTB Quests 1605 is no longer in beta, I will try to fix this in the next update.

**Comment by Hunter19823** [comment]
Fixed in v1.0.5
